#!/bin/sh
res=0

die() {
    [ -z "${HOOKS_KEEP_GOING}" ] && exit 1
    res=1
}

uv run --frozen ruff check nanachan/ || die
uv run --frozen ruff format --check --diff nanachan/ || die
uv run --frozen fawltydeps || die
if [ -n "${HOOKS_PYRIGHT_CHECK}" ]; then
    uv run --frozen pyright || die
fi

exit ${res}
