#!/bin/sh
uv run --frozen ruff check nanachan/ || exit 1
uv run --frozen ruff format --check --diff nanachan/ || exit 1
if [ -n "$HOOKS_PYRIGHT_CHECK" ]; then
    uv run --frozen pyright || exit 1
fi
